import uuid
import asyncio
import re
from datetime import datetime
from typing import List, Dict, Any

from shared.database.mongodb import get_db
from shared.schemas.obligation import BatchExtractionResult, Obligation
from shared.schemas.pipeline import ExecutionContext
from agents.base import BaseAgent
from shared.services.llm import LLMService
from shared.prompts.obligation_prompt import OBLIGATION_SYSTEM_PROMPT, OBLIGATION_HUMAN_PROMPT
from shared.services.logger import Logger

class ObligationExtractionAgent(BaseAgent):

    # Pre-screen regex heuristic:
    # Used to quickly filter out clauses that have no chance of being an obligation.
    # By strictly checking for these mandatory compliance verbs, we save money and 
    # time by bypassing the LLM entirely for purely structural or definitional text.
    PRE_SCREEN_REGEX = re.compile(
        r'\b(shall|must|required|ensure|maintain|submit|keep|provide|conduct|report|comply|implement)\b',
        # Matchs to 
        # "shall", "SHALL", "Shall"
        # "must", "Must"
        # "required", "REQUIRED"
        # "ensure", "maintain", "submit", "keep", "provide", "conduct", "report", "comply", "implement"
        re.IGNORECASE
    )

    @classmethod
    async def execute(cls, context: ExecutionContext) -> ExecutionContext:
        """
        Executes the MVP Obligation Extraction Pipeline:
        1. Fetch Segmented Clauses
        2. Run Heuristic Pre-Screen
        3. Batch Clauses for LLM (Phase 3 Optimization)
        4. Call LLM for Batches
        5. Validate Schema & Grounding
        6. Calculate Composite Confidence
        7. Store Results
        """
        document_id = context.document_id
        Logger.info("ObligationExtractionAgent", f"Started for {document_id}")
        db = get_db()
        
        # Initialize an audit log for this specific extraction run.
        # This mirrors the segmentation audit log and ensures traceability.
        run_id = f"EXT-{uuid.uuid4().hex[:8].upper()}"
        extraction_run = {
            "run_id": run_id,
            "circular_id": document_id,
            "segmentation_run_id": context.metadata.get("segmentation_run_id"),
            "started_at": datetime.utcnow(),
            "status": "RUNNING",
            "clauses_screened": 0,
            "clauses_sent_to_llm": 0,
            "obligations_created": 0,
            "clauses_skipped_no_obligation_language": 0,
            "skipped_clauses": [],
            "processed_clauses": [],
            "processed_clauses": [],
            "failed_clauses": []
        }
        
        await db.extraction_runs.insert_one(extraction_run)
        
        # We rely on the orchestrator to pass the clause_ids generated by the previous agent.
        clause_ids = context.metadata.get("clause_ids", [])
        if not clause_ids:
            Logger.warning("ObligationExtractionAgent", f"No clause_ids provided in context for {document_id}")
            await db.extraction_runs.update_one(
                {"run_id": run_id},
                {"$set": {
                    "status": "COMPLETED_EMPTY",
                    "completed_at": datetime.utcnow()
                }}
            )
            return context
            
        # 1. Fetch the actual clause documents from MongoDB using the provided IDs
        clauses = await db.clauses.find({"clause_id": {"$in": clause_ids}}).to_list(length=None)
        
        # Build a fast lookup map so we can easily fetch a parent clause's text later.
        clause_map = {c["clause_id"]: c for c in clauses}
        
        candidate_clauses = []
        for clause in clauses:
            extraction_run["clauses_screened"] += 1
            text = clause.get("text", "")
            
            # 2. Pre-screen Heuristic
            # If the clause doesn't contain a mandatory verb, skip the LLM call entirely.
            if not cls.PRE_SCREEN_REGEX.search(text):
                extraction_run["clauses_skipped_no_obligation_language"] += 1
                extraction_run["skipped_clauses"].append({
                    "clause_id": clause["clause_id"],
                    "reason": "Failed pre-screen (no mandatory language)"
                })
                continue
                
            candidate_clauses.append(clause)

        extraction_run["clauses_sent_to_llm"] = len(candidate_clauses)
        
        # Phase 3: Batching candidate clauses into groups of 10 to save API calls and avoid rate limits.
        BATCH_SIZE = 10
        # HACKATHON OPTIMIZATION: To prevent instantly blowing past Groq's 12,000 TPM limit on the free tier, 
        # we will limit the MVP extraction to the first 40 candidate clauses (4 batches).
        if len(candidate_clauses) > 40:
            Logger.warning("ObligationExtractionAgent", f"Truncating candidates from {len(candidate_clauses)} to 40 to respect Groq Free Tier TPM limits.")
            for skipped_c in candidate_clauses[40:]:
                extraction_run["skipped_clauses"].append({
                    "clause_id": skipped_c["clause_id"],
                    "reason": "Truncated due to TPM limit"
                })
            candidate_clauses = candidate_clauses[:40]
            
        batches = [candidate_clauses[i:i + BATCH_SIZE] for i in range(0, len(candidate_clauses), BATCH_SIZE)]
        
        Logger.info("ObligationExtractionAgent", f"Extracting obligations from {len(candidate_clauses)} candidate clauses across {len(batches)} batches using LLM Service...")
        
        doc_metadata = context.metadata.get("metadata_input", {})
        doc_title = doc_metadata.title if hasattr(doc_metadata, 'title') else "Unknown"
        doc_type = doc_metadata.document_type if hasattr(doc_metadata, 'document_type') else "Unknown"
        doc_date = doc_metadata.publication_date if hasattr(doc_metadata, 'publication_date') else "Unknown"

        all_pending_obligations = []
        
        # Concurrency limit to simulate Celery workers and prevent API flooding
        semaphore = asyncio.Semaphore(2)

        async def process_batch(batch_clauses):
            async with semaphore:
                try:
                    clauses_text = ""
                    for clause in batch_clauses:
                        parent_text = "None"
                        if clause.get("parent_clause_id") and clause["parent_clause_id"] in clause_map:
                            parent_text = clause_map[clause["parent_clause_id"]].get("text", "None")

                        hierarchy = " > ".join(clause.get("hierarchy_path", []))
                        
                        clauses_text += f"Clause ID: {clause['clause_id']}\n"
                        clauses_text += f"Hierarchy: {hierarchy}\n"
                        clauses_text += f"Parent Context: {parent_text}\n"
                        clauses_text += f"Text: {clause['text']}\n\n"

                    # 3. LLM Extraction Call (1 call per batch of 10)
                    result = await LLMService.generate_structured(
                        system_prompt=OBLIGATION_SYSTEM_PROMPT,
                        human_prompt=OBLIGATION_HUMAN_PROMPT,
                        schema=BatchExtractionResult,
                        input_vars={
                            "doc_title": doc_title,
                            "doc_type": doc_type,
                            "doc_date": doc_date,
                            "clauses_text": clauses_text
                        }
                    )
                    
                    # Throttle heavily between batches to let the Groq TPM bucket refill
                    await asyncio.sleep(4)
                    
                    extracted = []
                    batch_clause_map = {c["clause_id"]: c for c in batch_clauses}
                    
                    for clause_result in result.results:
                        clause_id = clause_result.clause_id
                        clause = batch_clause_map.get(clause_id)
                        
                        if not clause:
                            extraction_run["failed_clauses"].append({
                                "clause_id": clause_id,
                                "error": "LLM returned an unknown or hallucinated clause_id"
                            })
                            continue
                            
                        for ob in clause_result.obligations:
                            if not ob.is_obligation:
                                continue 
                                
                            grounding_score = 1.0
                            ambiguity_flags = []
                            text_lower = clause["text"].lower()
                            
                            def verify_field(field_val, field_name):
                                nonlocal grounding_score
                                if field_val and field_val.lower() not in text_lower:
                                    ambiguity_flags.append(f"{field_name}_not_found")
                                    grounding_score -= 0.25

                            verify_field(ob.applicable_entity, "entity")
                            verify_field(ob.deadline, "deadline")
                            verify_field(ob.frequency, "frequency")
                            verify_field(ob.evidence_type, "evidence")
                            
                            if ob.obligation_text and ob.obligation_text.lower() not in text_lower:
                                ambiguity_flags.append("obligation_text_not_found")
                                grounding_score -= 0.40
                            
                            grounding_score = max(0.0, grounding_score)
                            
                            if grounding_score < 1.0:
                                ambiguity_flags.append("possible_hallucination")

                            rule_score = 0.0
                            if ob.applicable_entity: rule_score += 0.15
                            if ob.deadline: rule_score += 0.10
                            if ob.frequency: rule_score += 0.10
                            if ob.evidence_type: rule_score += 0.10
                            
                            if "may " in text_lower or "at its discretion" in text_lower:
                                rule_score -= 0.20
                                
                            if ob.cross_reference_targets or re.search(r'(read with|as per clause|annexure)', text_lower):
                                rule_score -= 0.15
                                
                            parent_clause_used = False
                            if ob.parent_context_used:
                                rule_score -= 0.10
                                parent_clause_used = True
                                
                            composite_confidence = (0.4 * ob.llm_confidence) + (0.3 * rule_score) + (0.3 * grounding_score)
                            composite_confidence = max(0.0, min(1.0, composite_confidence))

                            doc = ob.model_dump()
                            doc["obligation_id"] = f"OBL-{uuid.uuid4().hex[:8].upper()}"
                            doc["clause_id"] = clause["clause_id"]
                            doc["circular_id"] = document_id
                            doc["clause_number"] = clause.get("clause_number")
                            doc["extraction_run_id"] = run_id
                            doc["grounding_score"] = grounding_score
                            doc["ambiguity_flags"] = ambiguity_flags
                            doc["parent_clause_used"] = parent_clause_used
                            doc["confidence"] = composite_confidence
                            doc["status"] = "PENDING_VALIDATION" 
                            doc["created_at"] = datetime.utcnow()
                            
                            extracted.append(doc)

                        extraction_run["processed_clauses"].append(clause["clause_id"])
                        
                    return extracted
                    
                except Exception as e:
                    Logger.error("ObligationExtractionAgent", f"Failed to extract obligations for batch", exc=e)
                    for c in batch_clauses:
                        extraction_run["failed_clauses"].append({
                            "clause_id": c["clause_id"],
                            "error": str(e)
                        })
                    return []
                
        results = await asyncio.gather(*[process_batch(batch) for batch in batches])
        
        # Flatten the list of lists returned by asyncio.gather
        for r_list in results:
            all_pending_obligations.extend(r_list)
            
        extraction_run["obligations_created"] = len(all_pending_obligations)
            
        if all_pending_obligations:
            # 6. Store the final validated obligations in MongoDB and update doc/run status atomically
            status = "COMPLETED" if not extraction_run["failed_clauses"] else "COMPLETED_WITH_FAILURES"
            
            async with await db.client.start_session() as session:
                async with session.start_transaction():
                    await db.obligations.insert_many(all_pending_obligations, session=session)
                    
                    await db.raw_documents.update_one(
                        {"document_id": document_id},
                        {"$set": {"status": "OBLIGATIONS_EXTRACTED"}},
                        session=session
                    )
                    
                    await db.extraction_runs.update_one(
                        {"run_id": run_id},
                        {"$set": {
                            "status": status,
                            "completed_at": datetime.utcnow(),
                            "clauses_screened": extraction_run["clauses_screened"],
                            "clauses_sent_to_llm": extraction_run["clauses_sent_to_llm"],
                            "obligations_created": extraction_run["obligations_created"],
                            "clauses_skipped_no_obligation_language": extraction_run["clauses_skipped_no_obligation_language"],
                            "skipped_clauses": extraction_run["skipped_clauses"],
                            "processed_clauses": extraction_run["processed_clauses"],
                            "failed_clauses": extraction_run["failed_clauses"]
                        }},
                        session=session
                    )
        else:
            status = "COMPLETED" if not extraction_run["failed_clauses"] else "COMPLETED_WITH_FAILURES"
            await db.raw_documents.update_one(
                {"document_id": document_id},
                {"$set": {"status": "OBLIGATIONS_EXTRACTED"}}
            )
            await db.extraction_runs.update_one(
                {"run_id": run_id},
                {"$set": {
                    "status": status,
                    "completed_at": datetime.utcnow(),
                    "clauses_screened": extraction_run["clauses_screened"],
                    "clauses_sent_to_llm": extraction_run["clauses_sent_to_llm"],
                    "obligations_created": extraction_run["obligations_created"],
                    "clauses_skipped_no_obligation_language": extraction_run["clauses_skipped_no_obligation_language"],
                    "skipped_clauses": extraction_run["skipped_clauses"],
                    "processed_clauses": extraction_run["processed_clauses"],
                    "failed_clauses": extraction_run["failed_clauses"]
                }}
            )
        
        # Make extraction details available to the next downstream agent (Review Queue)
        context.metadata["extraction_run_id"] = run_id
        
        Logger.info("ObligationExtractionAgent", f"Finished for {document_id}. Found {len(all_pending_obligations)} pending obligations.")
        return context
